<template>
  <div class="loader">
    <div class="loadingio-spinner-rolling-y5w14dw0es"><div class="ldio-mze9t2k6e9">
      <div></div>
    </div></div>
  </div>

</template>

<script>
export default {
  name: "Loader"
}
</script>

<style >
.loader {
  display: flex;
  align-items: center;
  justify-content: center;
}
@keyframes ldio-mze9t2k6e9 {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-mze9t2k6e9 div {
  position: absolute;
  width: 50px;
  height: 50px;
  border: 10px solid #634ce9;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-mze9t2k6e9 div {
  animation: ldio-mze9t2k6e9 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-y5w14dw0es {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: inherit;
}
.ldio-mze9t2k6e9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mze9t2k6e9 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>